field: 38b2411d-8417-45a2-823a-2d10dd554253
fieldLayouts:
  6bc53c89-9b7a-4ee9-b396-d51deae2149d:
    tabs:
      -
        elements:
          -
            fieldUid: de3ddd32-8581-44d4-a459-9a9c5993e7f7 # Label
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: afe79a28-798d-4313-b835-58eefb49a892
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 41abcfe5-0c1e-4a72-811d-b20ea97849dc
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b6a31648-cd00-48f2-915a-6b3e97bc167d
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 83f2a123-09f9-49c0-b9b3-22292ed87baa
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  41abcfe5-0c1e-4a72-811d-b20ea97849dc:
    contentColumnType: integer(10)
    fieldGroup: null
    handle: minValue
    instructions: ''
    name: 'Min Value'
    searchable: true
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: null
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Number
  83f2a123-09f9-49c0-b9b3-22292ed87baa:
    contentColumnType: boolean
    fieldGroup: null
    handle: required
    instructions: 'This field is required?'
    name: Required
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Lightswitch
  afe79a28-798d-4313-b835-58eefb49a892:
    contentColumnType: text
    fieldGroup: null
    handle: fieldHandle
    instructions: ''
    name: Handle
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  b6a31648-cd00-48f2-915a-6b3e97bc167d:
    contentColumnType: integer(10)
    fieldGroup: null
    handle: maxValue
    instructions: ''
    name: 'Max Value'
    searchable: true
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: null
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Number
  de3ddd32-8581-44d4-a459-9a9c5993e7f7: # Label
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: ''
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: number
name: Number
sortOrder: 5
