field: 38b2411d-8417-45a2-823a-2d10dd554253
fieldLayouts:
  bc8028c1-46f2-49ad-acc1-e8916bb4f26d:
    tabs:
      -
        elements:
          -
            fieldUid: 897c175b-1703-422b-bbf2-7f89c369aab8
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c9f0e9da-6bea-428c-91eb-825c19f75b93
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 731f8864-dab6-4ba1-b904-ec4a9f6ed6ef # Placeholder
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 758bc842-1be9-4067-a3bb-45d06d4405b6
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9fa20782-2d75-46f2-bc24-a4d3155e5c7b
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  731f8864-dab6-4ba1-b904-ec4a9f6ed6ef: # Placeholder
    contentColumnType: text
    fieldGroup: null
    handle: placeholder
    instructions: ''
    name: Placeholder
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  758bc842-1be9-4067-a3bb-45d06d4405b6:
    contentColumnType: integer(10)
    fieldGroup: null
    handle: initialRows
    instructions: ''
    name: 'Initial Rows'
    searchable: true
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: '2'
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Number
  897c175b-1703-422b-bbf2-7f89c369aab8:
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: ''
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  9fa20782-2d75-46f2-bc24-a4d3155e5c7b:
    contentColumnType: boolean
    fieldGroup: null
    handle: required
    instructions: 'This field is required?'
    name: Required
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Lightswitch
  c9f0e9da-6bea-428c-91eb-825c19f75b93:
    contentColumnType: text
    fieldGroup: null
    handle: fieldHandle
    instructions: ''
    name: Handle
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: paragraph
name: Paragraph
sortOrder: 2
