field: 28761c4b-a716-4ece-9edf-8eca45b41219 # Article Body
fieldLayouts:
  7adcf738-7f2e-4c39-b2cc-3be3f37b8412:
    tabs:
      -
        elements:
          -
            fieldUid: 14a20956-e4aa-47ec-9635-83899c828656 # Quote
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 94dd5ec8-cc65-44d1-a291-1bb052ae6b4a # Attribution
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d6b867a5-0607-422c-90a0-94febd0b4c95 # Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  14a20956-e4aa-47ec-9635-83899c828656: # Quote
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: ''
    name: Quote
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  94dd5ec8-cc65-44d1-a291-1bb052ae6b4a: # Attribution
    contentColumnType: text
    fieldGroup: null
    handle: attribution
    instructions: ''
    name: Attribution
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d6b867a5-0607-422c-90a0-94febd0b4c95: # Position
    contentColumnType: string
    fieldGroup: null
    handle: position
    instructions: ''
    name: Position
    searchable: true
    settings:
      default: center
      options:
        __assoc__:
          -
            - left
            - ''
          -
            - center
            - '1'
          -
            - right
            - ''
          -
            - full
            - '1'
          -
            - drop-left
            - ''
          -
            - drop-right
            - ''
    translationKeyFormat: null
    translationMethod: none
    type: rias\positionfieldtype\fields\Position
handle: quote
name: Quote
sortOrder: 7
