field: f1c57532-9589-45a9-b178-22beaea089aa # Fields
fieldLayouts:
  31823015-5343-4e66-bd9b-b29883a08392:
    tabs:
      -
        elements:
          -
            fieldUid: 72d3e057-299d-49ac-b29d-13505511101a
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9bb7ce66-72ed-410e-8f45-e8c80fad3955
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ce447bb3-7726-42ab-9b7a-55aa724c9e5b # Required
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 409991e5-3f46-4915-a8ae-71a8aa2d8b3e
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  409991e5-3f46-4915-a8ae-71a8aa2d8b3e:
    contentColumnType: text
    fieldGroup: null
    handle: instructions
    instructions: ''
    name: Instructions
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  72d3e057-299d-49ac-b29d-13505511101a:
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: ''
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9bb7ce66-72ed-410e-8f45-e8c80fad3955:
    contentColumnType: text
    fieldGroup: null
    handle: options
    instructions: ''
    name: Options
    searchable: true
    settings:
      addRowLabel: 'Add an option'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Label
                -
                  - handle
                  - label
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Value
                -
                  - handle
                  - value
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col3
            -
              __assoc__:
                -
                  - heading
                  - Selected
                -
                  - handle
                  - selected
                -
                  - width
                  - '50'
                -
                  - type
                  - lightswitch
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
            -
              - col3
              - ''
      maxRows: ''
      minRows: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  ce447bb3-7726-42ab-9b7a-55aa724c9e5b: # Required
    contentColumnType: boolean
    fieldGroup: null
    handle: required
    instructions: ''
    name: Required
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: select
name: Dropdown
sortOrder: 3
