field: 783e30e0-8d56-4802-ab10-2d66014098a0
fieldLayouts:
  c62a8bc9-567d-435c-bb2b-8ec557284535:
    tabs:
      -
        elements:
          -
            fieldUid: 83f27a9f-997b-4079-a25d-6ab9ef8aa837
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8210f3ad-8f8e-4c87-84ba-b4522e8e4c59
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e4d78861-f6e3-47e8-a726-78995f74d122 # Setup Fee
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 41ecd2e2-6d1c-4ac2-a079-6d997ee78ee4
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  41ecd2e2-6d1c-4ac2-a079-6d997ee78ee4:
    contentColumnType: boolean
    fieldGroup: null
    handle: default
    instructions: 'Please make sure that just one default is enabled'
    name: Default
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Lightswitch
  8210f3ad-8f8e-4c87-84ba-b4522e8e4c59:
    contentColumnType: text
    fieldGroup: null
    handle: customLabel
    instructions: 'Override the default text displayed for each plan (i.e. “Nickname amount/interval”)'
    name: 'Custom Label'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: 'Awesome Plan $35.00/month'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  83f27a9f-997b-4079-a25d-6ab9ef8aa837:
    contentColumnType: string
    fieldGroup: null
    handle: selectPlan
    instructions: 'Can''t see your plans? Go to [Subscriptions](http://kiss.test/cms-admin/enupal-stripe/settings/subscriptions) and click on Refresh Plans'
    name: 'Select Plan'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Select Plan...'
            -
              - value
              - ''
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Sponsor a Child £6.00/month'
            -
              - value
              - plan_F5NEvCQWGGK8ZH
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Dropdown
  e4d78861-f6e3-47e8-a726-78995f74d122: # Setup Fee
    contentColumnType: 'decimal(12,2)'
    fieldGroup: null
    handle: setupFee
    instructions: 'Setup Fee for the first payment'
    name: 'Setup Fee'
    searchable: true
    settings:
      decimals: '2'
      defaultValue: null
      max: null
      min: null
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Number
handle: subscriptionPlan
name: 'Subscription Plan'
sortOrder: 1
