fieldLayouts:
  c8a08684-fbeb-48d2-b6f9-7a3447d8e8f6:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 56c79704-f32e-426b-b557-8d4803fd785e # Body
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 6c52d467-6d5f-4a02-9b81-896972fe9294 # SEO
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
handle: newsIndex
hasTitleField: false
name: 'News Index'
section: 52701c8c-c37c-4982-9eb2-129960f0f7f3
sortOrder: 1
titleFormat: News
titleTranslationKeyFormat: null
titleTranslationMethod: site
