fieldLayouts:
  abd3074b-c6bc-4903-9910-2e7382dc9ba9:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 56c79704-f32e-426b-b557-8d4803fd785e # Body
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: resources
name: Resources
siteSettings:
  16d8c199-da90-4e47-84d1-fd46b342651b: # Kiddies Support Scheme
    hasUrls: true
    template: resources/_category
    uriFormat: 'resources/{slug}'
structure:
  maxLevels: 1
  uid: adaeefce-d4fb-4738-bd4a-30b7f27fbb47
