contentColumnType: text
fieldGroup: 2e6bbf3b-ca98-4dd3-8c78-1493f1e962ba # Globals
handle: copyrightNotice
instructions: ''
name: 'Copyright Notice'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
