contentColumnType: datetime
fieldGroup: 58aff042-feb1-42a8-b2c3-1795d837621b # Events
handle: date
instructions: 'Set the time to midnight (00:00) if you only want to display the date.'
name: Date
searchable: true
settings:
  max: null
  min: null
  minuteIncrement: '30'
  showDate: true
  showTime: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
