contentColumnType: text
fieldGroup: 2e6bbf3b-ca98-4dd3-8c78-1493f1e962ba # Globals
handle: instagramUrl
instructions: ''
name: 'Instagram URL'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: 'https://www.instagram.com/acme-limited'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
