enableVersioning: true
handle: donate
name: Donate
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  16d8c199-da90-4e47-84d1-fd46b342651b: # Kiddies Support Scheme
    enabledByDefault: true
    hasUrls: true
    template: donate/_index
    uriFormat: donate
type: single
