enableVersioning: true
handle: pages
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  16d8c199-da90-4e47-84d1-fd46b342651b: # Kiddies Support Scheme
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: 3
  uid: 8e2182b5-7c6a-4ba9-8597-559b902edd43
type: structure
